// Core budget measures for Power BI Desktop.
// Source workbook: Project_Finance_Tracker_1.xlsx

Approved Budget =
SUM ( Budget[Approved Amount] )

Actual Spend =
CALCULATE (
    SUM ( Invoices[Invoice Amount] ),
    KEEPFILTERS ( Invoices[Status] IN { "Paid", "Approved" } )
)

Paid Spend =
CALCULATE (
    SUM ( Invoices[Invoice Amount] ),
    KEEPFILTERS ( Invoices[Status] = "Paid" )
)

Approved Not Paid =
CALCULATE (
    SUM ( Invoices[Invoice Amount] ),
    KEEPFILTERS ( Invoices[Status] = "Approved" )
)

Pending Exposure =
CALCULATE (
    SUM ( Invoices[Invoice Amount] ),
    KEEPFILTERS ( Invoices[Status] = "Pending" )
)

Voided Amount =
CALCULATE (
    SUM ( Invoices[Invoice Amount] ),
    KEEPFILTERS ( Invoices[Status] = "Voided" )
)

Remaining Budget =
[Approved Budget] - [Actual Spend]

Over Cap Amount =
MAX ( 0, [Actual Spend] - [Approved Budget] )

Budget Used % =
DIVIDE ( [Actual Spend], [Approved Budget], 0 )

Contractor Count =
DISTINCTCOUNT ( Contractors[Contractor ID] )

Active Contractor Count =
CALCULATE (
    DISTINCTCOUNT ( Contractors[Contractor ID] ),
    KEEPFILTERS ( Contractors[Status] = "Active" )
)

Invoice Count =
DISTINCTCOUNT ( Invoices[Invoice ID] )

Pending Invoice Count =
CALCULATE (
    DISTINCTCOUNT ( Invoices[Invoice ID] ),
    KEEPFILTERS ( Invoices[Status] = "Pending" )
)

Approved Invoice Count =
CALCULATE (
    DISTINCTCOUNT ( Invoices[Invoice ID] ),
    KEEPFILTERS ( Invoices[Status] = "Approved" )
)

Paid Invoice Count =
CALCULATE (
    DISTINCTCOUNT ( Invoices[Invoice ID] ),
    KEEPFILTERS ( Invoices[Status] = "Paid" )
)

Change Log Entries =
COUNTROWS ( 'Change Log' )

Contractor Budget Remaining =
[Approved Budget] - [Actual Spend]

Contractor Budget Used % =
DIVIDE ( [Actual Spend], [Approved Budget], 0 )

Budget Risk Band =
SWITCH (
    TRUE (),
    [Over Cap Amount] > 0, "Over Cap",
    [Budget Used %] >= 0.85, "Critical",
    [Budget Used %] >= 0.60, "Caution",
    "Safe"
)
